spring.application.name=property-billing-api
server.port=${SERVER_PORT:8080}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.flyway.placeholders.initial_admin_id=${INITIAL_ADMIN_ID}
spring.flyway.placeholders.initial_admin_name=${INITIAL_ADMIN_NAME}
spring.flyway.placeholders.initial_admin_email=${INITIAL_ADMIN_EMAIL}
spring.flyway.placeholders.initial_admin_password_hash=${INITIAL_ADMIN_PASSWORD_HASH}
spring.flyway.placeholders.initial_admin_role=${INITIAL_ADMIN_ROLE}
